######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 4 19:52:39 2010
######################################################################

TEMPLATE = app
TARGET = tictactoe
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Board.h GuiBoard.h GuiButton.h
SOURCES += Board.cc GuiBoard.cc GuiButton.cc main.cc
